# ==============================================================================
# 脚本: 01_index_vcfs.R
# 目的: 为所有的 GWAS VCF 文件创建 Tabix (.tbi) 索引 (使用 R 语言)
#       这是运行 02_prepare_data.R 脚本（分块读取版）所必需的
# 作者: Generated by Gemini
# 日期: 2025-01-05
#
# 用法:
#   1. 确保你已安装了 Rsamtools:
#      if (!require("BiocManager", quietly = TRUE))
#          install.packages("BiocManager")
#      BiocManager::install("Rsamtools")
#   2. 直接在R中运行此脚本
# ==============================================================================

cat("
================================================================================
使用 Rsamtools 为 GWAS VCF 文件创建 Tabix 索引
================================================================================
\n")

# 加载包
if (!require("Rsamtools", quietly = TRUE)) {
  cat("错误: Rsamtools 包未安装。\n")
  cat("请先安装: \n")
  cat("if (!require(\"BiocManager\", quietly = TRUE))\n")
  cat("    install.packages(\"BiocManager\")\n")
  cat("BiocManager::install(\"Rsamtools\")\n")
  stop("Rsamtools is required.", call. = FALSE)
}

# --- 配置参数 (与 02_prepare_data.R 保持一致) ---

# 数据路径
RAW_GWAS_DIR <- "data/raw/gwas"

# 文件映射
GWAS_FILES <- list(
  BMI = "ieu-b-40.vcf.gz",
  CRP = "ebi-a-GCST90029070.vcf.gz",
  WBC = "ieu-b-30.vcf.gz",
  Alcohol = "ieu-b-73.vcf.gz",
  LUAD = "ieu-a-984.vcf.gz",
  LUSC = "ieu-a-989.vcf.gz"
)

# ------------------------------------------------------------------------------
# 主程序
# ------------------------------------------------------------------------------

cat("开始为 GWAS VCF 文件创建 Tabix 索引...\n")
cat("这将需要一些时间，具体取决于文件大小。\n\n")

# 循环遍历每个文件并创建索引
# 我们使用 `unlist` 来获取文件名向量
file_list <- unlist(GWAS_FILES)

for (file_name in file_list) {
  
  file_path <- file.path(RAW_GWAS_DIR, file_name)
  index_path <- paste0(file_path, ".tbi")
  
  cat(sprintf("--------------------------------------------------\n"))
  cat(sprintf("处理文件: %s\n", file_name))
  
  # 检查VCF文件是否存在
  if (!file.exists(file_path)) {
    cat(sprintf("  警告: 文件未找到 %s (跳过)\n", file_path))
    next
  }
  
  # 检查索引是否已存在
  if (file.exists(index_path)) {
    cat(sprintf("  索引已存在: %s (跳过)\n", index_path))
  } else {
    cat(sprintf("  正在为 %s 创建索引...\n", file_name))
    
    tryCatch({
      # 核心函数：创建索引
      # format = "vcf" 告诉 indexTabix 文件是 VCF 格式
      indexTabix(file = file_path, format = "vcf")
      
      cat(sprintf("  ✓ 成功创建索引: %s\n", index_path))
      
    }, error = function(e) {
      cat(sprintf("  ✗ 错误：无法为 %s 创建索引\n", file_name))
      cat(sprintf("    错误信息: %s\n", e$message))
      cat("    请确保VCF文件已正确排序 (按染色体，然后按位置)。\n")
    })
  }
}

cat("--------------------------------------------------\n")
cat("\n✓ 所有索引处理完毕！\n")
cat("现在你可以运行 02_prepare_data.R 脚本了。\n")